<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompletionRateOfTextResponses(variable)</name>
   <tag></tag>
   <elementGuidId>aeec128d-7f5d-4c5c-ab32-85cabf703d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[text()=${Question}]/..//div[@class=&quot;admin-survey__question-chart__meta&quot;]//p)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
