<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegisteredInstitutionUserNameOnTextAreaResponse(variable)</name>
   <tag></tag>
   <elementGuidId>c38e4a88-9ca1-4177-bac4-70d3864c1043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()=${Question}]/..//div[text()=&quot;${Visitor}&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
