<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeStampOnTextAreaResponse(variable)</name>
   <tag></tag>
   <elementGuidId>7c02da7c-3ec3-469e-93bc-cc6c3f5abfef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()=${Question}]/..//div[text()=&quot;${Date}&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
