<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditButton(id,institution)</name>
   <tag></tag>
   <elementGuidId>797e1961-8d11-46fb-807d-4000496c1799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;/institutions/${institution}/platform/mobi/instances/${id}/edit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;/institutions/${institution}/platform/mobi/instances/${id}/edit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
