<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstVisitTime</name>
   <tag></tag>
   <elementGuidId>0fae025d-1690-4a97-a406-c1cf7069171f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//li[@role=&quot;option&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//li[@role=&quot;option&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
