<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GroupsCheckBox</name>
   <tag></tag>
   <elementGuidId>ca0af48c-f690-47b2-8d20-19043a9244e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;input-mobiinstanceaudiences-groups&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;input-mobiinstanceaudiences-groups&quot;]</value>
   </webElementProperties>
</WebElementEntity>
