<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PreviewButtonOfDiscoveryFilter</name>
   <tag></tag>
   <elementGuidId>f31298ac-2f33-456b-a043-8645bf9b31c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr//td[text()='${DiscoveryInstanceName}']/..//td[@class=&quot;mobi-instance-list__table-cell-action&quot;][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr//td[text()='${DiscoveryInstanceName}']/..//td[@class=&quot;mobi-instance-list__table-cell-action&quot;][1]</value>
   </webElementProperties>
</WebElementEntity>
