<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DetailsTabInDailyVisits</name>
   <tag></tag>
   <elementGuidId>def2afa1-4de3-4999-9d60-84921cea4d6b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Details
    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember341&quot;)/div[@class=&quot;application-wrapper&quot;]/div[@class=&quot;app-main-body&quot;]/div[@class=&quot;container-fluid main-content-window&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-10 main-col no-padding&quot;]/div[@class=&quot;mobile-hide-overflow&quot;]/div[@class=&quot;v2&quot;]/div[@class=&quot;tabs hidden-xs&quot;]/a[@class=&quot;clickable&quot;]</value>
   </webElementProperties>
</WebElementEntity>
