<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HilightedVisitTypeInVisitTypeDropDownInDV</name>
   <tag></tag>
   <elementGuidId>209c6890-5a4e-4148-b60c-39c5339b734f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@aria-selected=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@aria-selected=&quot;false&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@aria-selected=&quot;true&quot;]</value>
   </webElementProperties>
</WebElementEntity>
