<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SinglecheckboxInAddVisitToItineraryModal</name>
   <tag></tag>
   <elementGuidId>782a0c83-88cf-4b13-a39b-88b5d36640c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div//div[@class=&quot;tooltip-help-icon&quot;]//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
