<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThreeDotMenuForCancelledVisits</name>
   <tag></tag>
   <elementGuidId>67cf3b3f-341a-44e9-a48e-947b817b41fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[text()=&quot;more_vert&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
