<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddLaterButtonInTeamsPhoto</name>
   <tag></tag>
   <elementGuidId>26f6cfd5-2c1a-4f15-8632-2fda27347440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;photo-buttons&quot;]//button[@type=&quot;button&quot;][2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
