<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyConventionNameInConventionStatsPage</name>
   <tag></tag>
   <elementGuidId>a8b242d2-3e2e-40f4-9a38-0782a220904a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;convention-providers-convention-stats__title-section&quot;]//div[text()='${ConventionName}']'</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
