<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AllCurrentAndFutureVisitTypesOption5</name>
   <tag></tag>
   <elementGuidId>9888edb8-e867-4894-b769-eeb3ca8a4b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for=&quot;input-whichvisittypes5-all&quot;]/..//input[@type='radio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
