<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AllCurrentAndFutureVisitTypesOption4</name>
   <tag></tag>
   <elementGuidId>a0416721-8177-4eff-a78e-3be6ea3b65d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for=&quot;input-whichvisittypes4-all&quot;]/..//input[@type='radio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
