<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AllCurrentAndFutureVisitTypesOption6</name>
   <tag></tag>
   <elementGuidId>bd5b43b0-0230-47ea-bbed-5954127dd6ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for=&quot;input-whichvisittypes6-all&quot;]/..//input[@type='radio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
