<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AllCurrentAndFutureVisitTypesOption1</name>
   <tag></tag>
   <elementGuidId>db0eddfa-8087-49ce-9fc7-be695efcd954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for=&quot;input-whichvisittypes1-all&quot;]/..//input[@type='radio']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
