<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpandButtonToViewSpecificVisitTypesChoiceTwo</name>
   <tag></tag>
   <elementGuidId>5b49798c-9c2b-48a3-89c3-26a216333993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[2]//span[contains(text(),'unfold_more')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
