<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpandButtonToViewSpecificVisitTypesChoiceOne</name>
   <tag></tag>
   <elementGuidId>d275cc41-8534-453e-a902-1606af687426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[1]//span[contains(text(),'unfold_more')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
