<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SecondAnswerChoiceText</name>
   <tag></tag>
   <elementGuidId>1f6c3599-d8cc-4955-bd1c-a8362fea93d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[2]//div[@class=&quot;question-form__answer-choice-controls&quot;]//input[@type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
