<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThreeDotMenuOfCreatedFilter</name>
   <tag></tag>
   <elementGuidId>06479135-fc90-4694-ac58-d67b3fb2321c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button//span[text()='more_vert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button//span[text()='more_vert']</value>
   </webElementProperties>
</WebElementEntity>
