<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VisitDaysLogo</name>
   <tag></tag>
   <elementGuidId>efef4535-3bea-44a1-b964-0c9bebef93d4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo2-70ba2f56917fb23399219bc1f8a9da4e.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember322&quot;)/div[@class=&quot;container container-fluid full-height-mobile&quot;]/div[@class=&quot;row full-height-mobile flex-center login-box-container&quot;]/div[@class=&quot;col-xs-12 login-box&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
