<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppliedOptionInApplicationStatus</name>
   <tag></tag>
   <elementGuidId>a5d02826-c774-47af-a0d0-b13a6733150c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[text()='${status}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='Applied']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[text()='${status}']</value>
   </webElementProperties>
</WebElementEntity>
