<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropdownOfQuestion(question)</name>
   <tag></tag>
   <elementGuidId>41ff4a8d-60f7-42f7-98d0-32f5a69e4313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='${question}']/..//div[@role=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='${question}']/..//div[@role=&quot;button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
