<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstOptionInHowManyGuestsDropdown</name>
   <tag></tag>
   <elementGuidId>04478eef-9710-4258-abe1-1c8e2e8a56b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[text()='${number}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text()='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[text()='${number}']</value>
   </webElementProperties>
</WebElementEntity>
