<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plusattendesymbol</name>
   <tag></tag>
   <elementGuidId>8911a12b-5d3e-47c3-a79d-a111a60e674e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[text()='add']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
