<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Registrantcheckinbottomtab</name>
   <tag></tag>
   <elementGuidId>e7a40208-db6b-4eae-bada-50d1d9e0db7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[text()='check']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
