<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimePendingLabelOfRequestVisitType(VisitType)</name>
   <tag></tag>
   <elementGuidId>c258cb9a-0caf-465d-a851-a83db27eee53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[text()='${VisitType}]/..//div[@class=&quot;itinerary-visit-time&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4[text()='${VisitType}]/..//div[@class=&quot;itinerary-visit-time&quot;]</value>
   </webElementProperties>
</WebElementEntity>
