<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyCreatedVisitsInMobi</name>
   <tag></tag>
   <elementGuidId>47dbb3a4-1551-4b6c-a64e-5a6305452376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div//h1[text()=&quot;${CreatedVisit}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div//h1[text()=&quot;${CreatedVisit}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
