<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UnsubscribeIconOnASpecificConversation(student)</name>
   <tag></tag>
   <elementGuidId>c2b47b37-4054-40c7-b867-92dd3133aa8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'${student}')]/../..//span[text()='speaker_notes_off']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'${student}')]/../..//span[text()='speaker_notes_off']</value>
   </webElementProperties>
</WebElementEntity>
