<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PendingRequestsCount</name>
   <tag></tag>
   <elementGuidId>69e22a6a-bbcd-426a-80c9-73e4a3cd19d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;app-navigation__item-badge&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;app-navigation__item-badge&quot;]</value>
   </webElementProperties>
</WebElementEntity>
