<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListChoice(index)</name>
   <tag></tag>
   <elementGuidId>e9b710ee-2c14-4c5d-9ab9-93501b9ec42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;question-form__answer-choice-controls&quot;]//input[@type=&quot;text&quot;])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;question-form__answer-choice-controls&quot;]//input[@type=&quot;text&quot;])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
