<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuestionNameTextField</name>
   <tag></tag>
   <elementGuidId>3be8a6e2-b073-4705-b42c-2f8c7008a974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@class=&quot;vd-slim-form__input&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@class=&quot;question-form__input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class=&quot;question-form__input&quot;]</value>
   </webElementProperties>
</WebElementEntity>
