<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DateDropdown</name>
   <tag></tag>
   <elementGuidId>b26d8d3a-6c82-4c0d-abcf-d4f7dfa11a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='Date']/..//div[@id=&quot;mui-component-select-meetingDate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='Date']/..//div[@id=&quot;mui-component-select-meetingDate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
