<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationsDropdown</name>
   <tag></tag>
   <elementGuidId>b305c534-fe33-4d08-94ba-c7937948f022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role=&quot;presentation&quot;]/preceding::div[contains(@class,'MuiPaper-rounded')]//p[text()='LOCATIONS']/..//input[not(@type=&quot;checkbox&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role=&quot;presentation&quot;]/preceding::div[contains(@class,'MuiPaper-rounded')]//p[text()='LOCATIONS']/..//input[not(@type=&quot;checkbox&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
