<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyFilterModalInLiveSessionsTab</name>
   <tag></tag>
   <elementGuidId>0547da5e-7ec5-4359-9cbf-6f3b2f6d6bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;css-12fbkww&quot;]//p[text()='LOCATIONS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
