<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsightsLeftNav</name>
   <tag></tag>
   <elementGuidId>57a61ff7-a4a6-4f7d-99cf-4e30145ef2d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[text()='Insights'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[text()='Insights'])[1]</value>
   </webElementProperties>
</WebElementEntity>
