<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InstitutionHeaderInSelfServe</name>
   <tag></tag>
   <elementGuidId>6a3c7265-a24d-47a8-aff8-c4b5f074abe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//th[text()='Institution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//th[text()='Institution']</value>
   </webElementProperties>
</WebElementEntity>
