<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LargestDisplaySizeOptionInDropDown</name>
   <tag></tag>
   <elementGuidId>f57f258e-f4fa-4606-b34d-975b924d624a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;vd-slim-form__container&quot;][last()]//div//select//option[@value=&quot;largest&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
