<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LargeDisplaySizeOptionInDropDown</name>
   <tag></tag>
   <elementGuidId>68e39091-3eda-4e0f-ba1d-36e03cc7d29e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;vd-slim-form__container&quot;][last()]//div//select//option[@value=&quot;large&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
