<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MediumDisplaySizeOptionInDropDown</name>
   <tag></tag>
   <elementGuidId>c69b76f5-583d-4988-ae80-7b7c7cdc6921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;vd-slim-form__container&quot;][last()]//div//select//option[@value=&quot;medium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
