<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SmallestDisplaySizeOptionInDropDown</name>
   <tag></tag>
   <elementGuidId>034a3fd9-0102-4bae-af0d-f336f4c24ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;vd-slim-form__container&quot;][last()]//div//select//option[@value=&quot;smallest&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
