<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RequestsOption</name>
   <tag></tag>
   <elementGuidId>970903d7-5d9b-4427-aca6-6cd53d3a34c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='Requests']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='REQUESTS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='Requests']</value>
   </webElementProperties>
</WebElementEntity>
