<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LocationHeader</name>
   <tag></tag>
   <elementGuidId>80a3e6dd-b392-4bca-b1c9-cb334d4ea887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[text()='Location']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
