<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StudentCheckBox</name>
   <tag></tag>
   <elementGuidId>921660ec-fbf5-4a02-b239-0291db0918de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//input[@value=&quot;student&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
