<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeleteVideoButtonInVideosPage</name>
   <tag></tag>
   <elementGuidId>7ae7db03-5607-47a7-b93d-105f97f311b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//span[contains(text(),'clear')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
