<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getNameOfFirstConvention</name>
   <tag></tag>
   <elementGuidId>acd38049-ff2a-4aca-9262-fdbb86a8c466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;conventions-convention-picker__item&quot;][1]//div[@class=&quot;conventions-convention-picker__name&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
