<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveButton</name>
   <tag></tag>
   <elementGuidId>f8853ea1-3f90-4404-a86a-b733f42baa87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[2]//button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
