<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectDropImg</name>
   <tag></tag>
   <elementGuidId>ff32b4be-ddea-4e1d-8eb9-66a370b57588</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@role=&quot;option&quot;]//span[@class=&quot;conventions-meeting-availability-form__assign-relationship-item&quot;])[${Index}]//img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
