<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectAssigneByDropDownSessions</name>
   <tag></tag>
   <elementGuidId>32978045-321a-47bb-b2c5-bf06edaa7aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@role=&quot;option&quot;]//span[@class=&quot;conventions-session-form__assign-relationship-item&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
