<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyAttendeesListOfScheduledMeeting</name>
   <tag></tag>
   <elementGuidId>fc6c3aa6-9563-4c6c-8dde-2fd87aca61ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;conventions-session-detail__attendees&quot;]//table//td[text()=&quot;${EMAIL}&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
