<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ViewMeetingsButtonInMeetingsPage</name>
   <tag></tag>
   <elementGuidId>e7a0f092-c802-4444-8e40-aaed65f28c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()=&quot;${AssigneeName}&quot;]/../../..//div[@class=&quot;conventions-meeting-availability-card__actions-left&quot;]//a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
