<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditConvention</name>
   <tag></tag>
   <elementGuidId>08c96047-bbc9-4c7e-b4ae-8bd7e423b88a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class=&quot;curator-convention-card__content&quot;]//div[text()='${ConventionName}']/../..//a[contains(@href,'/edit')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
