<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThreeDorMenuInConVentionsPageList</name>
   <tag></tag>
   <elementGuidId>41fe5ba2-f69e-403c-974d-0a65a1340487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class=&quot;curator-convention-card__content&quot;]//div[text()='${ConventionName}']/../..//div[@class=&quot;curator-convention-card__actions&quot;]//div[@class=&quot;curator-convention-card__actions-right&quot;]//a//i[text()='more_vert'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
