<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RemoveButtonInMyFairs</name>
   <tag></tag>
   <elementGuidId>230e0eb8-5375-4c4d-8a4a-bbe10a00396f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()=&quot;${SessionName}&quot;]/../..//button//span[text()=&quot;REMOVE&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
