<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectAssigneImg</name>
   <tag></tag>
   <elementGuidId>aca7b50a-0f5a-4804-9396-12088d7ff546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@role=&quot;option&quot;]//span[@class=&quot;conventions-meeting-availability-form__assign-relationship-item&quot;]//img)[${Index}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
