<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyCreatedQuestionPresent</name>
   <tag></tag>
   <elementGuidId>c9ecb186-fb9f-46e3-bbae-cf2fb950cc55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;sign-up-questions-card__content&quot;]//div[text()='${CreatedQuestion}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
