<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddressLineOne</name>
   <tag></tag>
   <elementGuidId>77990530-4a98-46ad-89e6-f33e6bb1f265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#addressLineOne</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#addressLineOne</value>
   </webElementProperties>
</WebElementEntity>
