<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddressLineTwo</name>
   <tag></tag>
   <elementGuidId>2838097f-8b8b-4809-9730-851ca60d1261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#addressLineTwo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#addressLineTwo</value>
   </webElementProperties>
</WebElementEntity>
