<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cityField</name>
   <tag></tag>
   <elementGuidId>4a1264cf-9c2f-4d4c-b80f-4be9bce8911c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#city</value>
   </webElementProperties>
</WebElementEntity>
