<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CountryDropdown</name>
   <tag></tag>
   <elementGuidId>b9a06626-b617-4659-85cd-22ee175aaba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>select[name=&quot;country&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>select[name=&quot;country&quot;]</value>
   </webElementProperties>
</WebElementEntity>
