<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CurrentOrLastSchoolField</name>
   <tag></tag>
   <elementGuidId>5d15cb18-059f-426f-bbd1-a69d3120aace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#school_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#school_name</value>
   </webElementProperties>
</WebElementEntity>
