<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dobField</name>
   <tag></tag>
   <elementGuidId>5c42ecc1-f084-4cc9-94d3-528458e9f890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#dob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#dob</value>
   </webElementProperties>
</WebElementEntity>
