<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GraduationYearField</name>
   <tag></tag>
   <elementGuidId>f156d612-156a-4cef-8ef5-5edc4543226d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#graduationYear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#graduationYear</value>
   </webElementProperties>
</WebElementEntity>
