<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LastNameFIeld</name>
   <tag></tag>
   <elementGuidId>838ab322-fff0-4c5e-b4b8-d0ee8750935d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#lastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#lastName</value>
   </webElementProperties>
</WebElementEntity>
