<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PhoneNumberField</name>
   <tag></tag>
   <elementGuidId>4b99edbd-4b69-4650-827a-6a5b2b7f6d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#phone</value>
   </webElementProperties>
</WebElementEntity>
