<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PostalCodeField</name>
   <tag></tag>
   <elementGuidId>44ebd60a-5f0b-4d50-b3d9-d2427d3865a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#postal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#postal</value>
   </webElementProperties>
</WebElementEntity>
