<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StateField</name>
   <tag></tag>
   <elementGuidId>03caccfc-feb4-4b41-86a9-c7de80204412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#state</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#state</value>
   </webElementProperties>
</WebElementEntity>
