<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survey-QuestionsTab</name>
   <tag></tag>
   <elementGuidId>7a82bee0-ecc7-4b68-ac2c-b04db4b12db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[text()='Questions'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[text()='Questions'])[1]</value>
   </webElementProperties>
</WebElementEntity>
