<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectedInsitution(institution)</name>
   <tag></tag>
   <elementGuidId>790b93be-3f8a-4bf3-8a90-3dbf475e5bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='check']/../..//div[text()='${institution}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='check']/../..//div[text()='${institution}']</value>
   </webElementProperties>
</WebElementEntity>
