<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AudienceErrorField</name>
   <tag></tag>
   <elementGuidId>7f957e24-6f15-4ebe-b531-69a7e95f3d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='Audience']/../../..//div[@class=&quot;mobi-question-form__error&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='Audience']/../../..//div[@class=&quot;mobi-question-form__error&quot;]</value>
   </webElementProperties>
</WebElementEntity>
