<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditButton(index)</name>
   <tag></tag>
   <elementGuidId>863fb3a6-b09b-4ce7-9566-51263a99ed40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;mdc-card__action-buttons&quot;])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;mdc-card__action-buttons&quot;])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
