<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmptyPlaceBelowTheQuestions</name>
   <tag></tag>
   <elementGuidId>d6415da9-2696-4c50-9b09-5e4a3d0c46f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;layout__intercom-spacer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;layout__intercom-spacer&quot;]</value>
   </webElementProperties>
</WebElementEntity>
