<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpecificVisitTypeRadioButton</name>
   <tag></tag>
   <elementGuidId>edeb52ee-bf0e-420b-b0c9-91b76f0798d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value=&quot;enabled_specific_visit_types&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value=&quot;enabled_specific_visit_types&quot;]</value>
   </webElementProperties>
</WebElementEntity>
