<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreatedTeamInTeamList(TeamName)</name>
   <tag></tag>
   <elementGuidId>9296557c-5fe9-4f1d-83f0-f25ce87d1023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;team-detail&quot;][text()=&quot;${TeamName}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;team-detail&quot;][text()=&quot;${TeamName}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
