<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonNameoFGivenSetting(setting)</name>
   <tag></tag>
   <elementGuidId>c2ac877f-7111-4d4f-b938-1cbe5cf4eaa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[text()='${setting}']/..//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[text()='${setting}']/..//a</value>
   </webElementProperties>
</WebElementEntity>
