<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EndTimeOfConventionMinute</name>
   <tag></tag>
   <elementGuidId>ed199dd5-cbc0-4498-8dc9-9cf8c3f7fec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=&quot;convention_convention_end_at_local_5i&quot;]//option[@value='59']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
