<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Survey_app_yieldHeader</name>
   <tag></tag>
   <elementGuidId>d7f78b9b-20f0-4c3c-855e-6503db483f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1[text()='surveys_app_yield']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1[text()='surveys_app_yield']</value>
   </webElementProperties>
</WebElementEntity>
