<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegiteredInvidualStudent</name>
   <tag></tag>
   <elementGuidId>fd9adacc-5700-4520-b710-b1c5f04ce053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='uservisit-entry-content']//div[text()='${Individual}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='uservisit-entry-content']//div[text()='${Individual}']</value>
   </webElementProperties>
</WebElementEntity>
