<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IUnderStoodThisActionCannotBeUndoneCheckBoxInCancelRegistrationModal</name>
   <tag></tag>
   <elementGuidId>a57afaad-e1fa-4350-a9a1-3f72b313fc52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for=&quot;cancel-reg-understood&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
