<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfigurationNav</name>
   <tag></tag>
   <elementGuidId>6d7fd3c5-95ee-4f23-b136-b885ddf58c58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Configuration']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//a[text()='Questions'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[text()='Questions'])[1]</value>
   </webElementProperties>
</WebElementEntity>
